apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres1  # Using the variable for the cluster name
  namespace: cnpg-cluster  # Using the variable for the namespace
  labels:
    cnpg.io/cluster: postgres1  # Using the variable for the cluster label
spec:
  namespaceSelector:
    matchNames:
      - cnpg-cluster  # Using the variable for the namespace
  selector:
    matchLabels:
      cnpg.io/cluster: postgres1  # Using the variable for the cluster label
  podMetricsEndpoints:
  - port: metrics  # Replace this with the actual port name if needed

