apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: pg-superuser
  namespace: cnpg-cluster
data:
  password: c3VwZXJ1c2Vy #secret_password
  username: cG9zdGdyZXM= #postgres - Note: It NEEDs to be postgres
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: pg-app-user
  namespace: cnpg-cluster
data:
  password: ZGVmYXVsdHVzZXI= #secret_password
  username: emVzcG9sMTQ= #zespol14
---
